export type VrinkLocation = {
  id: string;
  name: string;
  city: string;
  district: string;
  address: string;
  images: {
    src: string;
    alt: string;
  }[];
  lat: number;
  lng: number;
  mapPosition: {
    x: number;
    y: number;
  };
};

export function blankLocationImages(name: string) {
  return [1, 2, 3].map((imageNumber) => ({
    src: `/images/vrink/locations/blank-location-photo-${imageNumber}.svg`,
    alt: `${name} 설치 이미지 준비 중 ${imageNumber}`,
  }));
}

export const vrinkLocations: VrinkLocation[] = [
  {
    id: "bysec-world-fitness",
    name: "바이젝월드피트니스",
    city: "서울",
    district: "역삼동",
    address: "서울특별시 강남구 언주로85길 13 경남아파트 지하1층",
    images: blankLocationImages("바이젝월드피트니스"),
    lat: 37.500740753806,
    lng: 127.0420971394,
    mapPosition: { x: 48, y: 68 },
  },
  {
    id: "ojim-wonju",
    name: "오짐",
    city: "원주",
    district: "우산동",
    address: "강원특별자치도 원주시 모란1길 69 3층",
    images: blankLocationImages("오짐"),
    lat: 37.3688,
    lng: 127.9382,
    mapPosition: { x: 72, y: 73 },
  },
  {
    id: "gym90-city-hall-station",
    name: "짐구공 시청역점",
    city: "서울",
    district: "시청역점",
    address: "서울특별시 중구 서소문로 115 1층 102호, 103호",
    images: blankLocationImages("짐구공 시청역점"),
    lat: 37.5631,
    lng: 126.9742,
    mapPosition: { x: 43, y: 45 },
  },
  {
    id: "gym90-city-hall",
    name: "짐구공 시청점",
    city: "서울",
    district: "시청점",
    address: "서울특별시 중구 세종대로 64 2층 210호",
    images: blankLocationImages("짐구공 시청점"),
    lat: 37.561,
    lng: 126.9761,
    mapPosition: { x: 44, y: 47 },
  },
  {
    id: "west-gym-gangbyeon",
    name: "웨스트짐 강변점",
    city: "서울",
    district: "강변점",
    address: "서울특별시 광진구 구의강변로 86 지층",
    images: blankLocationImages("웨스트짐 강변점"),
    lat: 37.5359,
    lng: 127.0915,
    mapPosition: { x: 58, y: 43 },
  },
  {
    id: "west-gym-guui",
    name: "웨스트짐 구의점",
    city: "서울",
    district: "구의점",
    address: "서울특별시 광진구 자양로 86 세경빌딩 B1층",
    images: blankLocationImages("웨스트짐 구의점"),
    lat: 37.5369,
    lng: 127.0827,
    mapPosition: { x: 56, y: 46 },
  },
  {
    id: "able-gym-sangam",
    name: "에이블짐 상암",
    city: "서울",
    district: "상암동",
    address: "서울 마포구 월드컵북로56길 9 우리기술빌딩 지하1층",
    images: blankLocationImages("에이블짐 상암"),
    lat: 37.58143,
    lng: 126.88744,
    mapPosition: { x: 47.0, y: 40.2 },
  },
  {
    id: "able-gym-balsan",
    name: "에이블짐 발산",
    city: "서울",
    district: "내발산동",
    address: "서울 강서구 강서로 348 지하1층",
    images: blankLocationImages("에이블짐 발산"),
    lat: 37.55659,
    lng: 126.83798,
    mapPosition: { x: 44.0, y: 46.6 },
  },
  {
    id: "fore-wellness-gwacheon",
    name: "포레웰니스",
    city: "과천",
    district: "갈현동",
    address: "경기 과천시 과천대로6가길 39 과천자이엘라에디션 3층",
    images: blankLocationImages("포레웰니스"),
    lat: 37.41111,
    lng: 126.98222,
    mapPosition: { x: 41.8, y: 77.6 },
  },
  {
    id: "ss-fitness-gwanggyo",
    name: "더블에스휘트니스 광교1",
    city: "수원",
    district: "광교점",
    address: "경기 수원시 영통구 광교호수공원로 277 B2층",
    images: [
      {
        src: "/images/vrink/locations/double-s-fitness-gwanggyo.jpg",
        alt: "더블에스휘트니스 광교1에 설치된 브링크 제로스테이션 전경",
      },
      {
        src: "/images/vrink/locations/double-s-fitness-gwanggyo-front.jpg",
        alt: "더블에스휘트니스 광교1 브링크 설치 공간 정면 이미지",
      },
      {
        src: "/images/vrink/locations/double-s-fitness-gwanggyo-side.jpg",
        alt: "더블에스휘트니스 광교1 브링크 설치 공간 측면 이미지",
      },
    ],
    lat: 37.28115,
    lng: 127.05913,
    mapPosition: { x: 38.0, y: 97.0 },
  },
  {
    id: "vrink-headquarters-hanam",
    name: "브링크 본사",
    city: "하남",
    district: "감일동",
    address: "경기 하남시 동남로406번길 46 1, 2층",
    images: blankLocationImages("브링크 본사"),
    lat: 37.5097983,
    lng: 127.1431279,
    mapPosition: { x: 61.0, y: 60.0 },
  },
  {
    id: "dgym-yeongju",
    name: "디짐",
    city: "영주",
    district: "가흥동",
    address: "경상북도 영주시 대학로261번길 5",
    images: blankLocationImages("디짐"),
    lat: 36.81883,
    lng: 128.60263,
    mapPosition: { x: 69.3, y: 97.0 },
  },
  {
    id: "hawkeye-gym-wonju-2",
    name: "호크아이짐 2호",
    city: "원주",
    district: "반곡동",
    address: "강원특별자치도 원주시 오리현길 36",
    images: blankLocationImages("호크아이짐 2호"),
    lat: 37.33919,
    lng: 127.96991,
    mapPosition: { x: 73.1, y: 78.8 },
  },
  {
    id: "gym90-ssangmun",
    name: "짐구공 쌍문점",
    city: "서울",
    district: "쌍문동",
    address: "서울 도봉구 해등로 218 5층",
    images: blankLocationImages("짐구공 쌍문점"),
    lat: 37.65815,
    lng: 127.03263,
    mapPosition: { x: 56.0, y: 20.4 },
  },
  {
    id: "gym90-hufs",
    name: "짐구공 외대점",
    city: "서울",
    district: "휘경동",
    address: "서울 동대문구 휘경로 13 더305빌딩 B1",
    images: blankLocationImages("짐구공 외대점"),
    lat: 37.59601,
    lng: 127.0617,
    mapPosition: { x: 53.9, y: 34.2 },
  },
  {
    id: "gym90-gwanghwamun",
    name: "짐구공 광화문점",
    city: "서울",
    district: "무교동",
    address: "서울 중구 무교로 16 9층, 10층",
    images: blankLocationImages("짐구공 광화문점"),
    lat: 37.56733,
    lng: 126.97913,
    mapPosition: { x: 49.5, y: 42.0 },
  },
  {
    id: "gym90-gildong",
    name: "짐구공 길동점",
    city: "서울",
    district: "길동",
    address: "서울 강동구 양재대로 1457 B1, B2층",
    images: blankLocationImages("짐구공 길동점"),
    lat: 37.53751,
    lng: 127.14108,
    mapPosition: { x: 53.7, y: 46.3 },
  },
  {
    id: "star-gym-23-cheongdam",
    name: "스타짐23",
    city: "서울",
    district: "청담동",
    address: "서울 강남구 영동대로 722 풍양빌딩 4~5층",
    images: blankLocationImages("스타짐23"),
    lat: 37.5223927,
    lng: 127.0564078,
    mapPosition: { x: 53.0, y: 59.0 },
  },
  {
    id: "fitness-m-mapo",
    name: "휘트니스엠 마포점",
    city: "서울",
    district: "마포점",
    address: "서울 마포구 마포대로 33 한화 오벨리스크 지하 1층",
    images: blankLocationImages("휘트니스엠 마포점"),
    lat: 37.5399848,
    lng: 126.9454474,
    mapPosition: { x: 40.5, y: 54.0 },
  },
  {
    id: "mansumugang-health-andong",
    name: "만수무강헬스",
    city: "안동",
    district: "용상동",
    address: "경북 안동시 길주1길 28",
    images: blankLocationImages("만수무강헬스"),
    lat: 36.5527385,
    lng: 128.7637693,
    mapPosition: { x: 78.0, y: 95.0 },
  },
  {
    id: "gym-for-you-yullyang",
    name: "짐포유",
    city: "청주",
    district: "율량동",
    address: "충북 청주시 청원구 율봉로176번길 8-2 성일빌딩 2층",
    images: blankLocationImages("짐포유"),
    lat: 36.6685453,
    lng: 127.4882785,
    mapPosition: { x: 38.0, y: 91.0 },
  },
  {
    id: "aone-gym-dongtan-station",
    name: "에이원짐 동탄점",
    city: "화성",
    district: "동탄역점",
    address: "경기 화성시 동탄구 동탄역로 124 6층 602호",
    images: blankLocationImages("에이원짐 동탄점"),
    lat: 37.1975611,
    lng: 127.0965879,
    mapPosition: { x: 49.0, y: 86.0 },
  },
];
