export type VrinkLocation = {
  id: string;
  name: string;
  city: string;
  district: string;
  address: string;
  images: {
    src: string;
    alt: string;
  }[];
  lat: number;
  lng: number;
  mapPosition: {
    x: number;
    y: number;
  };
};

export function blankLocationImages(name: string) {
  return [1, 2, 3].map((imageNumber) => ({
    src: `/images/vrink/locations/blank-location-photo-${imageNumber}.svg`,
    alt: `${name} 설치 이미지 준비 중 ${imageNumber}`,
  }));
}

export const vrinkLocations: VrinkLocation[] = [
  {
    id: "buildup-fitness-seongsu",
    name: "빌드업피트니스 PT 성수역점",
    city: "서울",
    district: "성수역점",
    address: "서울 성동구 아차산로 97 남영빌딩 3층",
    images: [
      {
        src: "/images/vrink/locations/build-up-fitness-seongsu.jpg",
        alt: "빌드업피트니스 성수역점에 설치된 브링크 제로스테이션 전경",
      },
      {
        src: "/images/vrink/locations/build-up-fitness-seongsu-wide.jpg",
        alt: "빌드업피트니스 성수역점 브링크 설치 공간 와이드 이미지",
      },
      {
        src: "/images/vrink/locations/build-up-fitness-seongsu-station.jpg",
        alt: "빌드업피트니스 성수역점 리셉션 옆 브링크 설치 이미지",
      },
    ],
    lat: 37.5459,
    lng: 127.0547,
    mapPosition: { x: 51, y: 42 },
  },
  {
    id: "fitvely-celebrity-gym",
    name: "핏블리 연예인짐",
    city: "서울",
    district: "성수동",
    address: "서울특별시 성동구 연무장19길 6",
    images: blankLocationImages("핏블리 연예인짐"),
    lat: 37.5448,
    lng: 127.0588,
    mapPosition: { x: 54, y: 41 },
  },
  {
    id: "bysec-world-fitness",
    name: "바이젝월드피트니스",
    city: "서울",
    district: "역삼동",
    address: "서울특별시 강남구 언주로85길 13 경남아파트 지하1층",
    images: blankLocationImages("바이젝월드피트니스"),
    lat: 37.500740753806,
    lng: 127.0420971394,
    mapPosition: { x: 48, y: 68 },
  },
  {
    id: "ojim-wonju",
    name: "오짐",
    city: "원주",
    district: "우산동",
    address: "강원특별자치도 원주시 모란1길 69 3층",
    images: blankLocationImages("오짐"),
    lat: 37.3688,
    lng: 127.9382,
    mapPosition: { x: 72, y: 73 },
  },
  {
    id: "gym90-city-hall-station",
    name: "짐구공 시청역점",
    city: "서울",
    district: "시청역점",
    address: "서울특별시 중구 서소문로 115 1층 102호, 103호",
    images: blankLocationImages("짐구공 시청역점"),
    lat: 37.5631,
    lng: 126.9742,
    mapPosition: { x: 43, y: 45 },
  },
  {
    id: "gym90-city-hall",
    name: "짐구공 시청점",
    city: "서울",
    district: "시청점",
    address: "서울특별시 중구 세종대로 64 2층 210호",
    images: blankLocationImages("짐구공 시청점"),
    lat: 37.561,
    lng: 126.9761,
    mapPosition: { x: 44, y: 47 },
  },
  {
    id: "dallyeora-korean-medicine-clinic",
    name: "달려라한의원",
    city: "안양",
    district: "안양동",
    address: "경기도 안양시 만안구 장내로125번길 13, 중앙프라자 1층",
    images: blankLocationImages("달려라한의원"),
    lat: 37.3998,
    lng: 126.9221,
    mapPosition: { x: 39, y: 78 },
  },
  {
    id: "west-gym-gangbyeon",
    name: "웨스트짐 강변점",
    city: "서울",
    district: "강변점",
    address: "서울특별시 광진구 구의강변로 86 지층",
    images: blankLocationImages("웨스트짐 강변점"),
    lat: 37.5359,
    lng: 127.0915,
    mapPosition: { x: 58, y: 43 },
  },
  {
    id: "west-gym-guui",
    name: "웨스트짐 구의점",
    city: "서울",
    district: "구의점",
    address: "서울특별시 광진구 자양로 86 세경빌딩 B1층",
    images: blankLocationImages("웨스트짐 구의점"),
    lat: 37.5369,
    lng: 127.0827,
    mapPosition: { x: 56, y: 46 },
  },
  {
    id: "able-gym-sangam",
    name: "에이블짐 상암역점",
    city: "서울",
    district: "상암동",
    address: "서울 마포구 월드컵북로56길 9 우리기술빌딩 지하1층",
    images: blankLocationImages("에이블짐 상암역점"),
    lat: 37.58143,
    lng: 126.88744,
    mapPosition: { x: 47.0, y: 40.2 },
  },
  {
    id: "able-gym-balsan",
    name: "에이블짐 발산역점",
    city: "서울",
    district: "내발산동",
    address: "서울 강서구 강서로 348 지하1층",
    images: blankLocationImages("에이블짐 발산역점"),
    lat: 37.55659,
    lng: 126.83798,
    mapPosition: { x: 44.0, y: 46.6 },
  },
  {
    id: "fore-wellness-gwacheon",
    name: "포레웰니스",
    city: "과천",
    district: "갈현동",
    address: "경기 과천시 과천대로6가길 39 과천자이엘라에디션 3층",
    images: blankLocationImages("포레웰니스"),
    lat: 37.41111,
    lng: 126.98222,
    mapPosition: { x: 41.8, y: 77.6 },
  },
  {
    id: "ss-fitness-gwanggyo",
    name: "더블에스휘트니스 광교",
    city: "수원",
    district: "광교",
    address: "경기 수원시 영통구 광교호수공원로 277 B2층",
    images: blankLocationImages("더블에스휘트니스 광교"),
    lat: 37.28115,
    lng: 127.05913,
    mapPosition: { x: 38.0, y: 97.0 },
  },
  {
    id: "dgym-yeongju",
    name: "디짐",
    city: "영주",
    district: "가흥동",
    address: "경상북도 영주시 대학로261번길 5",
    images: blankLocationImages("디짐"),
    lat: 36.81883,
    lng: 128.60263,
    mapPosition: { x: 69.3, y: 97.0 },
  },
  {
    id: "hawkeye-gym-wonju-2",
    name: "호크아이짐 2호",
    city: "원주",
    district: "반곡동",
    address: "강원특별자치도 원주시 오리현길 36",
    images: blankLocationImages("호크아이짐 2호"),
    lat: 37.33919,
    lng: 127.96991,
    mapPosition: { x: 73.1, y: 78.8 },
  },
  {
    id: "gym90-ssangmun",
    name: "짐구공 쌍문점",
    city: "서울",
    district: "쌍문동",
    address: "서울 도봉구 해등로 218 5층",
    images: blankLocationImages("짐구공 쌍문점"),
    lat: 37.65815,
    lng: 127.03263,
    mapPosition: { x: 56.0, y: 20.4 },
  },
  {
    id: "gym90-hufs",
    name: "짐구공 외대점",
    city: "서울",
    district: "휘경동",
    address: "서울 동대문구 휘경로 13 더305빌딩 B1",
    images: blankLocationImages("짐구공 외대점"),
    lat: 37.59601,
    lng: 127.0617,
    mapPosition: { x: 53.9, y: 34.2 },
  },
  {
    id: "gym90-gwanghwamun",
    name: "짐구공 광화문점",
    city: "서울",
    district: "무교동",
    address: "서울 중구 무교로 16 9층, 10층",
    images: blankLocationImages("짐구공 광화문점"),
    lat: 37.56733,
    lng: 126.97913,
    mapPosition: { x: 49.5, y: 42.0 },
  },
  {
    id: "gym90-gildong",
    name: "짐구공 길동점",
    city: "서울",
    district: "길동",
    address: "서울 강동구 양재대로 1457 B1, B2층",
    images: blankLocationImages("짐구공 길동점"),
    lat: 37.53751,
    lng: 127.14108,
    mapPosition: { x: 53.7, y: 46.3 },
  },
];
