/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const fallbackProjectId = "odjnidzoerrygtaivuru";
const fallbackAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kam5pZHpvZXJyeWd0YWl2dXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0ODc3NTcsImV4cCI6MjA4NzA2Mzc1N30.4a3UT7qvpJERQWhcZG8Y0oSqVxHkYVZBRCBVQKayMNI";

const envProjectId = typeof import.meta !== "undefined"
  ? import.meta.env?.VITE_SUPABASE_PROJECT_ID
  : undefined;
const envAnonKey = typeof import.meta !== "undefined"
  ? import.meta.env?.VITE_SUPABASE_ANON_KEY
  : undefined;

export const projectId = (envProjectId && envProjectId.trim()) || fallbackProjectId;
export const publicAnonKey = (envAnonKey && envAnonKey.trim()) || fallbackAnonKey;
export const appEnv = (typeof import.meta !== "undefined" ? import.meta.env?.VITE_APP_ENV : undefined) || "dev";
